### PR TITLE
async file upload & avoid redundant copying

### PR DESCRIPTION
**Pull request by malb**
Perhaps async isn't your cup of tea, though.

### CODE REVIEW

**Comment by SRoskamp** [comment]
I've just moved the whole file/upload-interaction to a backend function for more extensibility, so I can't directly merge your suggestion. 

What advantages would the async file uploading bring with it?

EDIT: Also, wouldn't this introduce a dependency on async.el?

**Comment by malb** [comment]
Hi, yep, that'd introduce that dependency. The advantage would be that you can upload bigger files without Emacs hanging.

**Comment by SRoskamp** [comment]
I think it's a good idea to give the user the choice like you did. I'll look at how to merge it into the new structure now.

**Comment by SRoskamp** [comment]
I have merged your suggestion and modified the encrypted upload accordingly. Thanks!

**Comment by malb** [comment]
Excellent, thanks!

**Pull request merged**
